version: "3.8"
services:
  app:
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      DB_HOST: db
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    command: yarn dev
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db
